github:
  repo: cloudinaryLtd/cloudinary

interests:
  keywords:
    - "permissions"
    - "migration"
    - "authntication"
    - "accounts"
    - "user"
    - "auth"
    - "authorization"
    - "CSAM"
    - "notification"
    - "email"
    - "billing"
    - "recurly"
    - "usage"
    - "pricing"
    - "PDP"
    - "Cedar"
    - "Provisioning"
    - "Sub-account"
    - "Sub_account"
    - "subscription"
    - "account"
    - "organization"
    - "template"
  teams:
    - name: accounts
      ownership_file: server/config/teams/accounts.yml
    - name: billing
      ownership_file: server/config/teams/billing.yml

notifications:
  email_to: "asi@cloudinary.com"
  on_new_pr: true
  on_code_change: true
  on_merge: true
